annotator/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import include
from django.urls import reverse
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', RedirectView.as_view(url='demo/'), name='redirect-demo'),
    url(r'^demo/', include('demo.urls')),
    url(r'^userstudy/', include('userstudy.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/',auth_views.LoginView.as_view()),
]

demo/urls.py
from django.conf.urls import  url 
from . import views 
app_name='demo'
urlpatterns=[

	url(r'^$',views.select_input, name='select_input'),
    #url(r'^select_input$', views.select_input, name="select_input"),
    url(r'^text_input$', views.process_plain_text, name="process_plain_text"),
    url(r'^file_input$', views.process_file, name="process_file"),
    url(r'^url_input$', views.process_url, name="process_url"),
]

userstudy/urls.py
from django.conf.urls import  url 
from . import views 
app_name='userstudy'
urlpatterns=[

	url(r'^$',views.HomePageView.as_view(), name='home'),
	url(r'^(?P<pk>[0-9]+)/$',views.MentionDetailView.as_view(), name='detail'),
	url(r'^(?P<mention_table_id>[0-9]+)/submit$',views.submit_answer, name='submit_answer'),
	url(r'^done$', views.DoneView.as_view(), name='all_done'),
	url(r'^next$', views.next_mention_table, name='next'),
	url(r'^manual', views.AnnotationManual.as_view(), name='annotation_manual'),
	url(r'^page/(?P<page_id>[0-9]+)/$', views.page_view, name='page_view'),
	url(r'^pagepreview/(?P<pk>[0-9]+)/$', views.PagePreviewView.as_view(), name='page_preview'),
	url(r'^document/(?P<document_id>[0-9]+)/skip$', views.skip_document, name='skip_document'),
	url(r'^mention/(?P<mention_id>[0-9]+)/skip$', views.skip_mention, name='skip_mention'),
	url(r'^assignuser/(?P<page_id>[0-9]+)/', views.assign_user, name="assign_user"),
	url(r'^imprint$', views.ImprintView.as_view(), name="imprint"),
	url(r'^dataprotection', views.DataProtectionView.as_view(), name ="data_protection"),
	url(r'^selectdocument/(?P<page_id>[0-9]+)/', views.add_documents_to_batch, name="select_document"),
	url(r'^endsession/(?P<mention_id>[0-9]+)/', views.end_session, name="end_session"),
	url(r'^mentionannotationview/(?P<pk>[0-9]+)/$', views.MentionAnnotationView.as_view(), name="mention_annotation"),
	url(r'^annotatedmentionlist/', views.list_annotated_mentions, name="list_annotated_mentions"),
	url(r'^ignoreannotation/(?P<pk>[0-9]+)/$', views.ignore_annotation, name="ignore_annotation"),
	url(r'^considerannotation/(?P<pk>[0-9]+)/$', views.consider_annotation, name="consider_annotation"),
	url(r'^mentiontabledone/(?P<pk>[0-9]+)/$', views.mention_table_done, name="mention_table_done"),
	url(r'^annotationswithcomments/', views.list_annotations_with_comments, name ="list_annotations_with_comments"),
        url(r'^singleannotations/', views.list_single_annotations, name ="list_single_annotations"),

]

userstudy/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect 
from django.views import generic
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import login,authenticate
from django.db.models import Q
from django.urls import reverse
from .models import Page,Document, Mention, Annotation, Mention_Table, Pool 	
from django.contrib.auth.models import User
from threading import Lock
from django.contrib.auth import logout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django import template
from django.template.defaulttags import register

lock = Lock()


@register.filter(name='get_item')
def get_item(dictionary, key):
	return dictionary[key]
@login_required
def list_annotated_mentions(request):

	mention_tables = Annotation.get_annotations_disagreements()
	paginator = Paginator(mention_tables, 100)	
	page = request.GET.get('page')
	try:
		mention_tables = paginator.page(page)
	except PageNotAnInteger:
	# If page is not an integer, deliver first page.
		mention_tables = paginator.page(1)
	except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        	mention_tables = paginator.page(paginator.num_pages)
	return render(request, 'userstudy/list_annotated_mentions.html', {'mention_tables': mention_tables})


@login_required 
def list_single_annotations(request):
	mention_tables = Annotation.get_single_annotated_mentions()
	paginator = Paginator(mention_tables,100)
	page = request.GET.get('page')
	try:
		mention_tables = paginator.page(page)
	except PageNotAnInteger:
		mention_tables = paginator.page(1)
	except EmptyPage:
		mention_tables = paginator.page(paginator.num_pages)
	return render(request, 'userstudy/list_annotated_mentions.html', {'mention_tables': mention_tables})

@login_required 
def list_annotations_with_comments(request):
	mention_tables = Annotation.get_annotations_with_comments()
	paginator = Paginator(mention_tables,100)
	page = request.GET.get('page')
	try:
		mention_tables = paginator.page(page)
	except PageNotAnInteger:
		mention_tables = paginator.page(1)
	except EmptyPage:
		mention_tables = paginator.page(paginator.num_pages)
	return render(request, 'userstudy/list_annotated_mentions.html', {'mention_tables': mention_tables})

@login_required
def page_view(request,page_id):
	page = get_object_or_404(Page, pk = page_id)
	return HttpResponse(page.html_content)


@login_required
def skip_mention(request, mention_id):
	mention= get_object_or_404(Mention, pk = mention_id)
	mention.skip = True
	mention.locked = False
	mention.save()
	return HttpResponseRedirect(reverse('userstudy:next'))
@login_required
def skip_document(request, document_id):
	document = get_object_or_404(Document, pk =document_id)
	document.skip = True
	document.save()
	return HttpResponseRedirect(reverse('userstudy:next'))
class ImprintView(generic.base.TemplateView):
	template_name = "userstudy/imprint.html"
class DataProtectionView(generic.base.TemplateView):
	template_name = "userstudy/data_protection.html"
	
class HomePageView(generic.base.TemplateView):
	template_name ="userstudy/home.html"
#	def get_context_data(self, **kwargs):
#        	context = super(HomePageView, self).get_context_data(**kwargs)
#        	context['latest_articles'] = Article.objects.all()[:5]
#        	return conte

#def index(request):
#	return HttpResponse("Hello, World!")

class DoneView(generic.base.TemplateView):
	template_name ="userstudy/done.html"
class AnnotationManual(generic.base.TemplateView):
	template_name = "userstudy/annotation_manual.html"

class PagePreviewView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
	model = Page
	template_name ='userstudy/page_preview.html'
	permission_required =('userstudy.change_page','userstudy.delete_page', 'userstudy.delete_document', 'userstudy.change_document')
	
	def get_context_data(self, **kwargs):
		context = super(PagePreviewView,self).get_context_data(**kwargs)
		context['user'] = self.request.user
		context['users'] = User.objects.all()
		return context
class MentionAnnotationView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
	model = Mention_Table
	template_name='userstudy/mention_annotation.html'
	permission_required = ('userstudy.change_annotation', 'userstudy.delete_annotation')
	def get_context_data(self, **kwargs):
		context = super(MentionAnnotationView,self).get_context_data(**kwargs)
		context['annotations']= Annotation.get_all_annotations(context['mention_table'].mention.id, context['mention_table'].table.id)
		if 'HTTP_REFERER' in self.request.META:
			ref = self.request.META['HTTP_REFERER']
			#print(ref)
		else:
			ref=''
		
		if "mentionannotationview" in ref or 'annotatedmentionlist' in ref:
			#print("ref contains mentionannotationview or annotatedmentionlist")
			context['load_next'] = 'False'
		else:
			context['load_next'] = 'True'
		#print(context)
		return context 		

@login_required
def ignore_annotation(request, pk):
	annotation = get_object_or_404(Annotation, pk= pk)
	annotation.ignore = True
	annotation.save()
	return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def consider_annotation(request, pk):
	annotation = get_object_or_404(Annotation, pk= pk)
	annotation.ignore = False
	annotation.save()
	return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def mention_table_done(request, pk):
	mention_table = get_object_or_404(Mention_Table, pk=pk)
	mention_table.checked = True
	mention_table.save()
	return HttpResponseRedirect(reverse('userstudy:list_single_annotations'))
    #HttpResponseRedirect(reverse('userstudy:list_annotations_with_comments')) #HttpResponseRedirect(reverse('userstudy:list_annotated_mentions'))


def add_documents_to_batch(request, page_id):
	page = get_object_or_404(Page, pk=page_id)
	#page.assigned_user = request.user
	#page.save()
	
	document_id_list = request.POST['document_id_list']
	action = request.POST['submit_page']
	pool = None
	if action == 'Boring Numbers':
		pool = Pool.objects.get(id =3)
	else:
		pool = Pool.get_active_pool()
	if not pool:
		return HttpResponseRedirect(reverse('userstudy:all_done'))
	if action != 'Ignore':
		page.assigned_user = request.user
		page.save()
		for document_id in document_id_list.split(','):
			if len(document_id.strip()) ==0:
				continue
			#print(document_id)
			document = Document.objects.get(id =int(document_id))
			document.pool = pool
			document.save()
	else:
		page.assigned_user = User.objects.get(id=11)
		page.save()

	next_page = Page.get_next_non_assigned_page()
	if next_page:
		return HttpResponseRedirect(reverse('userstudy:page_preview',args=(next_page.id,)))
	else:
		return HttpResponseRedirect(reverse('userstudy:all_done'))
def assign_user(request, page_id):
	page = get_object_or_404(Page, pk=page_id)
	user_id = request.POST['user_id']
	user = get_object_or_404(User, pk=user_id)
	page.assigned_user = user
	page.save()
	next_page = Page.get_next_non_assigned_page()
	if next_page:
		return HttpResponseRedirect(reverse('userstudy:page_preview',args=(next_page.id,)))
	else:
		return HttpResponseRedirect(reverse('userstudy:all_done'))
class MentionDetailView(LoginRequiredMixin,PermissionRequiredMixin ,generic.DetailView):
	model= Mention_Table
	template_name='userstudy/detail.html'
	permission_required = ('userstudy.add_annotation', 'userstudy.change_annotation',"userstudy.change_document", "userstudy.change_mention_table")
	
	def get_context_data(self, **kwargs):
		context = super(MentionDetailView, self).get_context_data(**kwargs)
		context['user'] = self.request.user
		annotation_count = Annotation.get_number_annotated(self.request.user.id) 
		#print(annotation_count)
		context['annotated_mentions'] = annotation_count
		if 'HTTP_REFERER' in self.request.META:
			ref = self.request.META['HTTP_REFERER']
		else:
			ref=''
		if "mentionannotationview" in ref:
			context['load_next'] = False
		else:
			context['load_next'] = True

		return context
@login_required 
def next_mention_table(request):
	next_mention_table_id = Mention_Table.get_next_mention_table(request.user)
	if( next_mention_table_id != -1):
		return HttpResponseRedirect(reverse('userstudy:detail',args=(next_mention_table_id,)))
	else:
		return HttpResponseRedirect(reverse('userstudy:all_done'))
@login_required 
def end_session(request, mention_id):
	mention = get_object_or_404(Mention, pk=mention_id)
	mention.locked = False
	mention.save()
	logout(request)
	return HttpResponseRedirect(reverse('userstudy:home'))
@login_required 
def submit_answer(request, mention_table_id):
	global lock
	mention_table  = get_object_or_404(Mention_Table,pk=mention_table_id)
	try:
		#print(request.POST)
		submit_btn = request.POST['submit_btn']
		#print(submit_btn)
		relation = request.POST['relation']
		load_next = request.POST['load_next']
		if load_next == 'True':
			load_next = True
		else:
			load_next = False

		if submit_btn ==  'Not a Mention':
			relation = 'Not Mention'
		elif submit_btn == 'Not Related':
			relation = 'Not Related'
		#print(relation)
		if relation == 'other':
			relation = request.POST['other_aggregate']
		if submit_btn == 'Exact':
			exact = 'True'
		else:
			exact = 'False'
		table_cells = request.POST['related_cells']
		#exact = request.POST['exact']
		user = request.user
		comment = request.POST['comment']
		if not (user.has_perm("userstudy.add_annotation") and user.has_perm("userstudy.change_document") and user.has_perm("userstudy.change_mention_table") ):
			return HttpResponseRedirect(reverse('userstudy:home'))
		#CREATE A NEW ANNOTaTION
		annotation = Annotation.objects.create(mention = mention_table.mention, table = mention_table.table, exact=exact,relation=relation,related_table_cells =table_cells, annotator= user,comment=comment)
		mention = mention_table.mention

userstudy/templates/userstudy/data_protection.html
{% extends "base_site.html" %}
  {% load i18n static %}
  
  {% block content %}
   {% block breadcrumbs %} {% endblock %}

<div id="c9293" class="box frame frame-default frame-type-text frame-layout-0"><header class="box_header"><h1 class="">
				Data Protection
			</h1></header><div class="box_content"><h2 class="underline">Data Protection</h2><h3>Data Collection and Processing</h3><p>Visits to this Website are logged. The anonymized IP address currently used by your computer, as well as further technical data pertaining to the data call is recorded.
</p><p>Session cookies are used within the scope of this Internet session for technical reasons. This data is deleted at the latest when you close your browser.
</p><p>Data is evaluated only for statistical purposes in anonymized form. No personal user profiles are created.
</p><p>The data protection officer of the Max Planck Society is available for questions concerning the topic of data protection at <a href="typo3/mailto:dsb@gv.mpg.de">dsb@gv.mpg.de</a> or +49 (0) 89-2108-1317.
</p><h3>Personalized Services / Newsletter</h3><p>If you would like to take advantage of a personalized service or to register for a newsletter service the required personal data are stored. As a rule this includes your email address, first name and surname as well as other data – depending on the type of offer. Your data are used only in order to provide you with the desired information to your satisfaction and in order to respond to any inquiries. If you no longer wish to take advantage of a personalized service, your personal data will be deleted after you cancel your registration. If you wish to cancel your subscription to a newsletter, you can either send us an e-mail, or carry out cancellation by using the respective link at the end of the newsletter.
</p><h3>Data Transmission</h3><p>Your personal data will only be transmitted to government organizations and authorities in legally required cases and/or for prosecution in the event of attacks on our network infrastructure. Your personal data are not provided to third parties for any other purpose.
</p><h2 class="underline">Liability for Contents of Online Information</h2><p>In accordance with Section 7 Paragraph 1 of the Tele-Media Law, the Max Planck Society shall be responsible for its own contents according to general legal provisions. The Max Planck Society makes every effort to provide timely and accurate information on this Website. Nevertheless, errors and inaccuracies cannot be completely ruled out. Therefore, the Max Planck Society does not assume any liability for the information provided being up-to-date as well as its accuracy, completeness or quality. The Max Planck Society shall not be liable for damage of a tangible or intangible nature caused directly or indirectly through the use or failure to use the information offered and/or through the use of faulty or incomplete information unless it is verifiably culpable of intent or gross negligence. The same shall apply to any software downloads available free of charge. The Max Planck Society reserves the right to modify, supplement, or delete any or all of the information offered on its Website, or to temporarily or permanently cease publication thereof without prior and separate notification.
</p><h2 class="underline">Links to Websites of Third Parties</h2><p>This Website includes links to other external websites. The respective provider shall be responsible for the contents of any linked external pages. In establishing the initial link, the Max Planck Society has reviewed the respective external content in order to determine whether such link entailed possible civil or criminal responsibility. However, a constant review of linked external pages is unreasonable without concrete indication of a violation of rights.. If the Max Planck Society discovers or is pointed out by others that an external offer linked to by the Max Planck Society causes civil or criminal responsibility, the Max Planck Society will immediately eliminate any link to this offer. The Max Planck Society expressly dissociates itself from such contents.</p></div></div>

 {% endblock %}

userstudy/templates/userstudy/detail.html
{% extends "base_site.html"%}
{% load  i18n static%}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static 'userstudy/css/detail.css' %}" /> {% endblock %}

{% block nav-global %}
<div align="right" class="end_session">
 Welcome {{ request.user.username }}! | Completed Records: {{ annotated_mentions }} |
 <a href="{% url 'userstudy:end_session' mention_table.mention_id%}"> End Session </a></div>
{% endblock %}


{% block content %}
  {% if error_message %}
  <p class="errornote">
      {{ error_message }}
  </p>
  {% endif %}

<div id="doc-text" class="text-part">
{% autoescape off %}
{{ mention_table.highlighted_mention_in_text }}
{% endautoescape %}
</div>
<div id="doc-table" class="table-part">
{% autoescape off %}

{{ mention_table.table_view}}
{% endautoescape %}
</div>
<form id="main_form" action="{% url 'userstudy:submit_answer' mention_table.id %}" method="post">
{% csrf_token %}

<div id="selections" class="selection-part">
 <!--  <div class="radio">
	<label> <input type="radio" name="relation" value="Not Mention"> Not A Mention </label>
   </div>
   <div class="radio">
        <label>  <input type="radio" name="relation" value="Not Related">  Not Related </label>
   </div>

   <div class="radio">
       Related with  [<label class="radio-inline">  <input type="radio" name="exact" value="False" > approximate  </lable>
       |<label class="radio-inline">  <input type="radio" name ="exact" value="True" checked> exact </lable>] value, and the type of relation is:
   </div> -->
<h4> Select the Type of Relation: </h4>
   <div class ="related">
	<div class="radio">
                <label> <input type="radio" name="relation" value="same" checked> Single Value  </label>
        </div>

  	<div class="radio">
        	<label> <input type="radio" name="relation" value="sum"> Sum  </label>
	</div>
        <div class="radio">
                <label> <input type="radio" name="relation" value="dif"> Difference  </label>
        </div>

        <div class="radio">
                <label> <input type="radio" name="relation" value="rat"> Decrease/Increase ratio  </label>
        </div>
        <div class="radio">
                <label> <input type="radio" name="relation" value="avg"> Average  </label>
        </div>

        <div class="radio">
                <label> <input type="radio" name="relation" value="max"> Max  </label>
        </div>

        <div class="radio">
                <label> <input type="radio" name="relation" value="min"> Min  </label>
        </div>
	<div class="radio">
		<label> <input type="radio" name="relation" value="percentage"> Percentage </label>
	</div>
	
	<div class="radio">
		<label> <input type= "radio" name="relation" value="range"> Range </label>
	</div>

	<div>
		<label> <input type="radio" name="relation" value="header"> Header </label>
	</div>

        <div class="radio">
                <label> <input type="radio" name="relation" value="other"> other <input type="text" name="other_aggregate" />  </label>
        </div>
</div>
	<div>
		<label> Comment: </label> <textarea name="comment" rows="2" cols="20"></textarea>
	</div>

</div>
<div class="submit-cls" id="submit">
<input type="submit" name="submit_btn"  value ="{% trans 'Not a Mention' %}"/>
<input type="submit" name="submit_btn"  value ="{% trans 'Not Related' %}"/>
<input type="submit" name="submit_btn"  value ="{% trans 'Exact' %}"/>
<input type="submit" name="submit_btn"  value ="{% trans 'Approximate' %}"/>
<input type="hidden" name="related_cells" />
<input type="hidden" name="load_next" value="{{load_next}}"/>
</div>
</form>
<div class='links'>
 <a href="{% url 'userstudy:skip_mention' mention_table.mention_id %}" > Skip This Mention </a> --
<a href="{% url 'userstudy:skip_document' mention_table.document_id %}" > Skip This Document </a> --
<a href="{% url 'userstudy:page_view' mention_table.document_page_id %}" > View Source Page </a>
</div>

{%endblock%}

{% block extrajavascript %}
<script src="{% static 'userstudy/js/detail.js' %}"></script>
{% endblock %}

userstudy/templates/userstudy/done.html
{% extends "base_site.html" %}
{% load i18n static %} 

{% block content %}
 {% block breadcrumbs %} {% endblock %} 
All records were annotated please contact your supervisor!
Thanks!
{% endblock %}

userstudy/templates/userstudy/home.html
{% extends "base_site.html" %}
{% load i18n static %} 

{% block content %}
 {% block breadcrumbs %} {% endblock %} 

This site collecte annotation for a table corpus extracted from Dresden Table Corpus, which in turn extracted from Common Crawl of July 2014. Please read the instructions <a href="{%url 'userstudy:annotation_manual' %}">available here </a>  and login when you are ready to start. Thank you for your support!
<a href="{% url 'login' %}">{% trans 'Login' %}!</a>
{% endblock %}

userstudy/templates/userstudy/list_annotated_mentions.html
{% extends "base_site.html"%}
{% load  i18n static%}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static 'userstudy/css/detail.css' %}" /> {% endblock %}

{% block nav-global %}
{% endblock %}


{% block content %}
  {% if error_message %}
  <p class="errornote">
      {{ error_message }}
  </p>
  {% endif %}


<ul>
{% for mention_table  in mention_tables  %}
<li>
    {{ mention_table| get_item:"mention" }} | <a href="{% url 'userstudy:mention_annotation' mention_table|get_item:"mention_table_id" %}"> Show Annotations </a>
</li>
{% endfor %}
</ul>
<div class="pagination">
    <span class="step-links">
        {% if mention_tables.has_previous %}
            <a href="?page=1">first</a>
            <a href="?page={{ mention_tables.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ mention_tables.number }} of {{ mention_tables.paginator.num_pages }}.
        </span>

        {% if mention_tables.has_next %}
            <a href="?page={{ mention_tables.next_page_number }}">next</a>
            <a href="?page={{ mention_tables.paginator.num_pages }}">last</a>
        {% endif %}
    </span>
</div>
{% endblock %}
{% block extrajavascript %}
<!-- <script src="{% static 'userstudy/js/detail.js' %}"></script>-->

{% endblock %}

userstudy/templates/userstudy/mention_annotation.html
{% extends "base_site.html"%}
{% load  i18n static%}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static 'userstudy/css/detail.css' %}" /> {% endblock %}
{% block content %}
  {% if error_message %}
  <p class="errornote">
      {{ error_message }}
  </p>
  {% endif %}

<h3> Mention:{{mention_table.mention__mention}}</h3>
<div class="text">
{% autoescape off %}
<div class="text"> {{mention_table.highlighted_mention_in_text}}</div>
{% endautoescape %}
 <div name="target-table" class="table">
{% autoescape off %}
{{ mention_table.table_view }}
{% endautoescape %}
</div>

</div>
<table>
<tr>
<th>Annotator Name </th>
<th>Relation </th>
<th> Related Cells </th>
<th>Comment</th>
<th>Type</th>
</tr>
{% for annotation in annotations%}
<tr>	
	<td> {{annotation.annotator_name}}</td>
	<td> {{ annotation.relation}}</td>
	<td> {{annotation.related_table_cells}} 
		<a href="#" onclick="highlight_cells('{{annotation.related_table_cells}}' )"> highlight </a> 
	</td>
	<td> {{annotation.comment}}</td>
	<td> {{annotation.relation_type}}</td>
	<td> 
		{% if annotation.ignore %}
			<a href="{% url 'userstudy:consider_annotation' annotation.id %}"> Consider </a>
		{% else %}
			<a href="{% url 'userstudy:ignore_annotation' annotation.id%}"> Ignore </a>	
		{%endif%}
	</td>
</tr>
{% endfor%}
</table>
<a href="{% url 'userstudy:detail' mention_table.id  %}"> Edit Annotation </a>
<br/>
<br/>
<a href="{% url 'userstudy:mention_table_done' mention_table.id  %}"> Done! </a>
{%endblock%}

{% block extrajavascript %}

	 <script src="{% static 'userstudy/js/mention_annotation.js' %}"></script>
{% endblock %}

userstudy/templates/userstudy/page_preview.html
{% extends "base_site.html"%}
{% load  i18n static%}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static 'userstudy/css/page_preview.css' %}" /> {% endblock %}
{% block content %}
  {% if error_message %}
  <p class="errornote">
      {{ error_message }}
  </p>
  {% endif %}

<h3> {{page.title}}</h3>

<a href="{% url 'userstudy:page_view' page.pk%}" target="_blank"> View Source Page </a>
<br/>

<form name="assign_user_to_page" action="{% url 'userstudy:select_document' page.id %}" method=POST>
{% csrf_token %}
<div class="select-user">
	<input type="submit" name="submit_page" value="Add to Batch"/>
	<input type="submit" name="submit_page" value="Ignore"/>
	<input type="submit" name="submit_page" value="Boring Numbers" />
	<input type="hidden" name="document_id_list"/>
</div>
</form>
<br/>
{% for document in page.document_set.all%}
		<h5> <span style="color:red">Text:</span></h5>
		<input type="checkbox" name="document_select" value="{{ document.id}}"/>	<div id="doc-text" class="text-part">
		{% autoescape off %}
	
			{{ document.highlighted_text }}
		{% endautoescape %}
		</div>
		<a href="{% url 'admin:userstudy_document_change' document.pk%}" target="_blank"> Edit Document </a>
	{% for mention in document.mention_set.all%}
		{% if mention.mention_table_set.all %}
			<div class="mention"> Mention: {{mention.mention}}, ID: {{mention.id}}</div>
			<div class="tables-title"> Related Tables:</div>
			{% for mention_table in mention.mention_table_set.all%}
				<div class="table">
					Table ID: {{mention_table.table_id}}<br/>
					{% autoescape off %}
						{{mention_table.table_view}}
					{% endautoescape %}
				</div>
			{% endfor %}
		{% endif %}
	{% endfor %}
{% endfor%}

<a href="{% url 'userstudy:page_view' page.pk%}" target="_blank"> View Source Page </a>
{%endblock%}

{% block extrajavascript %}
	 <script src="{% static 'userstudy/js/page_preview.js' %}"></script>
{% endblock %}