annotator/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls import include
from django.urls import reverse
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', RedirectView.as_view(url='demo/'), name='redirect-demo'),
    url(r'^demo/', include('demo.urls')),
    url(r'^userstudy/', include('userstudy.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/',auth_views.LoginView.as_view()),
]

demo/urls.py
from django.conf.urls import  url 
from . import views 
app_name='demo'
urlpatterns=[

	url(r'^$',views.select_input, name='select_input'),
    #url(r'^select_input$', views.select_input, name="select_input"),
    url(r'^text_input$', views.process_plain_text, name="process_plain_text"),
    url(r'^file_input$', views.process_file, name="process_file"),
    url(r'^url_input$', views.process_url, name="process_url"),
]

userstudy/urls.py
from django.conf.urls import  url 
from . import views 
app_name='userstudy'
urlpatterns=[

	url(r'^$',views.HomePageView.as_view(), name='home'),
	url(r'^(?P<pk>[0-9]+)/$',views.MentionDetailView.as_view(), name='detail'),
	url(r'^(?P<mention_table_id>[0-9]+)/submit$',views.submit_answer, name='submit_answer'),
	url(r'^done$', views.DoneView.as_view(), name='all_done'),
	url(r'^next$', views.next_mention_table, name='next'),
	url(r'^manual', views.AnnotationManual.as_view(), name='annotation_manual'),
	url(r'^page/(?P<page_id>[0-9]+)/$', views.page_view, name='page_view'),
	url(r'^pagepreview/(?P<pk>[0-9]+)/$', views.PagePreviewView.as_view(), name='page_preview'),
	url(r'^document/(?P<document_id>[0-9]+)/skip$', views.skip_document, name='skip_document'),
	url(r'^mention/(?P<mention_id>[0-9]+)/skip$', views.skip_mention, name='skip_mention'),
	url(r'^assignuser/(?P<page_id>[0-9]+)/', views.assign_user, name="assign_user"),
	url(r'^imprint$', views.ImprintView.as_view(), name="imprint"),
	url(r'^dataprotection', views.DataProtectionView.as_view(), name ="data_protection"),
	url(r'^selectdocument/(?P<page_id>[0-9]+)/', views.add_documents_to_batch, name="select_document"),
	url(r'^endsession/(?P<mention_id>[0-9]+)/', views.end_session, name="end_session"),
	url(r'^mentionannotationview/(?P<pk>[0-9]+)/$', views.MentionAnnotationView.as_view(), name="mention_annotation"),
	url(r'^annotatedmentionlist/', views.list_annotated_mentions, name="list_annotated_mentions"),
	url(r'^ignoreannotation/(?P<pk>[0-9]+)/$', views.ignore_annotation, name="ignore_annotation"),
	url(r'^considerannotation/(?P<pk>[0-9]+)/$', views.consider_annotation, name="consider_annotation"),
	url(r'^mentiontabledone/(?P<pk>[0-9]+)/$', views.mention_table_done, name="mention_table_done"),
	url(r'^annotationswithcomments/', views.list_annotations_with_comments, name ="list_annotations_with_comments"),
        url(r'^singleannotations/', views.list_single_annotations, name ="list_single_annotations"),

]

templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}" />
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}" />{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}


<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
<script src="https://unpkg.com/tooltip.js/dist/umd/tooltip.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">
 {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
		has permission
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
				user active!
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
      {% endif %} 
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
     <a href="{% url 'userstudy:home' %}">{% trans 'Home' %}</a> 
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

  {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

{% block extrajavascript %}{% endblock %}


</body>
</html>

templates/base_site.html
{% extends "base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Tables Annotation') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'userstudy:home' %}">Tables Annotation</a></h1>
{% endblock %}

{% block nav-global %}
{% endblock %}
{%block footer %} <div id="footer"> <a href="{% url 'userstudy:imprint' %}"> Imprint </a>|<a href="{% url 'userstudy:data_protection' %}"> Data Protection </a> </div> {% endblock %}